# Generated by Django 4.0.1 on 2022-07-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_employee_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(default='', upload_to='doc/'),
        ),
    ]
