# Generated by Django 4.0.1 on 2022-08-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_department_id_alter_employee_id_alter_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
    ]
